version: 2
jobs:
  deploy:
    docker:
    - image: jakubkoval/mina-deployer-docker
    working_directory: ~/circleci-demo-workflows
    steps:
    - checkout
    - run:
        name: Deploy Over SSH
        command: |
          mina deploy
    # - run: bundle install --path vendor/bundle  # install dependencies



workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        filters:
          branches:
            only: dev


