version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.3.4-node-jessie
    - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
    - checkout
    - run: bundle install --path vendor/bundle  # install dependencies
    - run: bundle exec rake db:create db:schema:load  # setup database
    - run:
        name: Run tests
        command: rake

  deploy:
    machine:
      enabled: true
    steps:
    - run:
        name: Deploy Over SSH
        command: |
          ssh $SSH_USER@$SSH_HOST "mina deploy"

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: dev


