version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/circleci-demo-workflows
    steps:
    - checkout
    - run: bundle install --path vendor/bundle  # install dependencies

  deploy:
    machine:
      enabled: true
    steps:
    - run:
        name: Deploy Over SSH
        command: |
          ssh $SSH_USER@$SSH_HOST "mina deploy"

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: dev


